### ISSUE TITLE
Apakah line update protocol?

### ISSUE THREAD

**Issue by kazereborn** [andyihsan/LIN3-TCR#12]
Traceback (most recent call last):
  File "line-tcr.py", line 13, in <module>
    cl.login(qr=True)
  File "/home/cabox/workspace/LIN3-TCR/LINETCR/LineApi.py", line 40, in login
    self.Poll = Poll(self.authToken)
  File "/home/cabox/workspace/LIN3-TCR/LINETCR/Api/Poll.py", line 35, in __init__
    self.rev = self.client.getLastOpRevision()
  File "/home/cabox/workspace/LIN3-TCR/LINETCR/Api/../lib/curve/LineService.py", line 9884, in getLastOpRevision
    return self.recv_getLastOpRevision()
  File "/home/cabox/workspace/LIN3-TCR/LINETCR/Api/../lib/curve/LineService.py", line 9895, in recv_getLastOpRevision
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TCompactProtocol.py", line 310, in readMessageBegin
    proto_id = self.__readUByte()
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TCompactProtocol.py", line 289, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 63, in readAll
    raise EOFError()
EOFError

**Comment by nazri07** [comment]
UA = "Line/7.14.0"
LA = "IOSIPAD\t7.14.0\tiPhone OS\t10.12.0"

**Comment by kazereborn** [comment]
@nazri07 work perfectly thannks
